# Generated by Django 4.2.2 on 2023-09-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_name', models.CharField(max_length=200)),
                ('Standard', models.CharField(max_length=50)),
                ('Aadhaar_no', models.IntegerField(max_length=12)),
                ('Age', models.IntegerField()),
                ('Cast', models.CharField(max_length=50)),
                ('Phone', models.CharField(max_length=20)),
                ('Address', models.TextField(max_length=500)),
                ('City', models.CharField(max_length=100)),
                ('District', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=100)),
                ('Reason', models.TextField()),
                ('Date', models.DateField()),
            ],
        ),
    ]
