# Generated by Django 4.2.5 on 2023-09-14 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_studentsinfo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsinfo',
            name='Student_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
